services:
  db:
    image: postgres:16.11-alpine3.23
    container_name: db
    restart: unless-stopped

    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 128M

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - ./data:/var/lib/postgresql/data

    ports:
      - "5432:5432"

  app:
    build: .
    container_name: app
    restart: unless-stopped

    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 128M

    ports:
      - "8000:8000"

    depends_on:
      - db
