"""work in progress

Revision ID: 01d7eb724836
Revises: fdc0e0d0a6d6
Create Date: 2026-06-12 00:14:13.321556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01d7eb724836'
down_revision: Union[str, Sequence[str], None] = 'fdc0e0d0a6d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('delayed_until', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('remind_after', sa.DateTime(), nullable=False))
    op.drop_column('tasks', 'next_time_to_do')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('next_time_to_do', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('tasks', 'remind_after')
    op.drop_column('tasks', 'delayed_until')
    op.drop_column('tasks', 'user_id')
    # ### end Alembic commands ###
