"""work in progress

Revision ID: 1c7e657f9cd1
Revises: 352ed1ce2c73
Create Date: 2026-06-10 15:16:50.561613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c7e657f9cd1'
down_revision: Union[str, Sequence[str], None] = '352ed1ce2c73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('next_time_to_do', sa.DateTime(), nullable=False))
    op.drop_column('tasks', 'last_time_done')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('last_time_done', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('tasks', 'next_time_to_do')
    # ### end Alembic commands ###
