"""work in progress

Revision ID: 4fe70d421ac7
Revises: 1c7e657f9cd1
Create Date: 2026-06-10 21:03:45.999458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fe70d421ac7'
down_revision: Union[str, Sequence[str], None] = '1c7e657f9cd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_repeatable', sa.Boolean(), nullable=False))
    op.alter_column('tasks', 'frequency_hours',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('tasks', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.alter_column('tasks', 'frequency_hours',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('tasks', 'is_repeatable')
    # ### end Alembic commands ###
