"""work in progress

Revision ID: 51ab51f65110
Revises: 
Create Date: 2026-06-12 00:21:23.963228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51ab51f65110'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('frequency_hours', sa.Integer(), nullable=True),
    sa.Column('delayed_until', sa.DateTime(), nullable=True),
    sa.Column('remind_after', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'id', name='pk_tasks_user_id_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###
