"""work in progress

Revision ID: fdc0e0d0a6d6
Revises: 4fe70d421ac7
Create Date: 2026-06-10 21:29:54.458001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdc0e0d0a6d6'
down_revision: Union[str, Sequence[str], None] = '4fe70d421ac7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'is_repeatable')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_repeatable', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
